sensors:
    uv_camera:              true
    zed_camera:             true
    gps_module:             true

camera:
    ros__parameters:
        resource:           "csi://0" #"v4l2:///dev/video0" #"csi://0" #"file:///home/cw-orin/Videos/videoplayback.mp4" #"v4l2:///dev/video0" "csi://0" 
        width:              1920
        height:             1080

stereo_camera:
    ros__parameters:
        device:             "/dev/video0"
        width:              3200        # Full stereo width (both cameras)
        height:             1300        # Height
        y16_format:         true        # Use Y16 format for Arducam
        use_gstreamer:      false       # Try V4L2 first, then GStreamer
        enable_left:        true
        enable_right:       true
        
preview:
    ros__parameters:
        output:             "display://0"
        width:              960
        height:             540        

detect:
    ros__parameters:
        model:              "detect.engine"
        labels:             "labels_detect.txt"        
        thresholds:
            - 0.40          # Applied to all object classes
            - 0.45           # Pedestrian objects
            - 0.45          # Cyclist objects
            - 0.6           # Vehicle-car objects
            - 0.45           # Vehicle-bus objects
            - 0.45           # Vehicle-truck objects
            - 0.5           # Vehicle-train objects
            - 0.40          # Traffic light objects            
            - 0.55          # Traffic sign objects
        track_frame_rate:   30          # Frame rate for tracking
        track_buffer:       30          # Buffer size for lost tracks

classify:
    ros__parameters:
        model:               "classify.engine"
        labels:              "labels_classify.txt"
        thresholds:
            - 0.30           # Traffic Light objects
            - 0.75           # Traffic Sign objects

lanedet:
    ros__parameters:
        model:              "lane_detect.engine"

